#!/bin/bash
#
#	corta los videos que tienen marcos en youtube
#

# entrada
ENTRADA="$*"

# capturas de panalla
ffmpegthumbnailer -i "$ENTRADA" -s 0 -t "15%" -o /tmp/15.png 2> /dev/null
ffmpegthumbnailer -i "$ENTRADA" -s 0 -t "75%" -o /tmp/75.png 2> /dev/null

# corte con la mascara
composite /tmp/15.png /tmp/75.png -compose difference /tmp/general.png 2> /dev/null

CORTE=$( convert /tmp/general.png -threshold 50% -format "%@" info: 2>  /dev/null | sed 's/x/:/g; s/+/:/g')
echo "$CORTE"

[ ! "$2" == "corte" ] && exit

DIR=$(dirname "$1")
BASE=$(basename "$1")

ffmpeg -i "$1" -filter:v "crop=$CORTE" -c:a copy  -y "$DIR/${BASE%%*.}-corte.${BASE##*.}"

